name       : python-aiohttp
version    : 3.5.4
release    : 2
source     :
    - https://github.com/aio-libs/aiohttp/archive/v3.5.4.tar.gz : 9385ff2ea20249be9119236b3367356465cb92dc55b463d12239c7cf36024bba
license    : Apache-2.0
component  : programming.python
summary    : Asynchronous HTTP client/server framework for asyncio and Python
description: |
    Asynchronous HTTP client/server framework for asyncio and Python
builddeps  :
    - cython
    - python-async_timeout
    - python-chardet
    - python-idna_ssl
    - python-multidict
    - python-typing
    - python-yarl
rundeps    :
    - python-async_timeout
    - python-chardet
    - python-idna_ssl
    - python-multidict
    - python-typing
    - python-yarl
build      : |
    %python3_setup
install    : |
    %python3_install
